---
- name: stop networkmager
  service: name=NetworkManager state=stopped enabled=no

- name: Check if firewalld is installed
  stat: path=/usr/lib/systemd/system/firewalld.service
  register: fw_file

- name: Disable firewalled if it is installed
  service: name=firewalld.service state=stopped enabled=no
  when: fw_file.stat.exists != False

- name: Update selinux config to Disabled mode
  selinux: policy=targeted state=disabled

- name: change sshd
  lineinfile:
     dest: /etc/ssh/sshd_config
     regexp: '{{ item.regexp }}'
     line: '{{ item.line }}'
  with_items:
    - { regexp: '.*UseDNS.*', line: 'UseDNS no' }
    - { regexp: '.*GSSAPIAuthentication.*', line: 'GSSAPIAuthentication no' }

- name: copy mariadb repo
  copy: src=files/MariaDB.repo dest=/etc/yum.repos.d/

- name: reboot system
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0

- name: waiting for server come back
  local_action: wait_for host={{ansible_host}} port=22 state=started delay=60 timeout=600
  become: no 
