---
- name: configure
  templates: src=templates/my.cnf.j2 dest=/etc/my.cnf

- name: mkdir
  file: path=/etc/systemd/system/mariadb.service.d state=directory

- name: config /etc/systemd/system/mariadb.service.d/limits.conf for limit
  template: src=templates/limits.conf.j2 dest=/etc/systemd/system/mariadb.service.d/limits.conf

- name: daemon-reload
  shell: systemctl daemon-reload

- name: start mariadb services
  service: name=mariadb state=started enabled=yes

- name: change database root password
  command: mysqladmin -u root password "{{ DB_ROOT_PASSWORD }}"
 
- name: database security enhancement for ha system
  command: mysql -u root -p{{ DB_ROOT_PASSWORD }} -e "{{ item }}"
  with_items:
    - "DELETE FROM mysql.user WHERE User='';"
    - "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';"
    - "GRANT ALL PRIVILEGES ON *.* to 'root'@'%' IDENTIFIED BY '{{ DB_ROOT_PASSWORD }}' WITH GRANT OPTION"
    - "GRANT ALL PRIVILEGES ON *.* to 'root'@'{{ ansible_hostname }}' IDENTIFIED BY '{{ DB_ROOT_PASSWORD }}' WITH GRANT OPTION"
    - "FLUSH PRIVILEGES;"



