- name: start mariadb services
  service: name=mariadb state=started enabled=yes
  when: ansible_hostname == groups.Mysql[0] 

- name: mysql secure installation
  copy: src=files/mysql_secure_installation.exp dest=/root/
  when: ansible_hostname == groups.Mysql[0]

- name: chmod
  file: path=/root/mysql_secure_installation.exp mode=777
  when: ansible_hostname == groups.Mysql[0]

- name: expect the mysql_secure_installation.exp
  command: ./mysql_secure_installation.exp
  when: ansible_hostname == groups.Mysql[0]

- name: stop mariadb services
  service: name=mariadb state=stopped
  when: ansible_hostname == groups.Mysql[0]
