- name: galera configure
  template: src=templates/server.cnf.j2 dest=/etc/my.cnf.d/server.cnf

- name: choice one node to build cluster
  command: /usr/bin/galera_new_cluster
  register: galeraclusterstatus
  until: galeraclusterstatus | success
  retries: 10
  delay: 3
  when: ansible_hostname == groups.Mysql[0]

- name: Restart node Galera cluster service
  service: name=mariadb state=started enabled=yes
  register: service_status
  until: service_status|success
  retries: 3
  delay: 5
  when: ansible_hostname != groups.Mysql[0]

- name: Restart node Galera cluster service
  service: name=mariadb state=restarted enabled=yes
  register: service_status
  until: service_status|success
  retries: 3
  delay: 5
  when: ansible_hostname == groups.Mysql[0]


