---
- name: Install mariadb packages
  yum: name={{ item }} state=present
  with_items:
    - mariadb-server
    - MariaDB-client
    - galera 
    - rsync
    - expect
  register: pkg_inst_result
  until: pkg_inst_result|success
  retries: 3
  delay: 5

